A= int(input())
B= int(input())
C= int(input())
D= int(input())
E= int(input())
F= int(input())
lst = []
lst2 = []
lst.append(A)
lst.append(B)
lst.append(C)
lst.append(D)
lst2.append(E)
lst2.append(F)
lst.remove(min(lst))
lst2.remove(min(lst2))
sum1 = sum(lst)
sum2 = sum(lst2)
print(sum1+sum2)